services:

  word-frequency.word-frequency-counter:
    class: WordFrequency\WordFrequencyCounter
    arguments:
      - '@word-frequency.words-to-array-converter'
      - '@word-frequency.array-values-counter'
      - '@word-frequency.array-sort-value-descending-key-ascending'

  word-frequency.words-to-array-converter:
    class: WordFrequency\WordsToArrayConverter
    public: false

  word-frequency.array-values-counter:
    class: WordFrequency\ArrayValuesCounter
    public: false

  word-frequency.array-sort-value-descending-key-ascending:
    class: WordFrequency\ArraySortValueDescendingKeyAscending
    public: false

  app.text-loader:
    class: App\TextLoader\TextLoader
