#!/usr/bin/env php
<?php

use App\Application;
use App\Command\WordFrequencyCommand;

require __DIR__ . '/../vendor/autoload.php';

$application = new Application();
$wordFrequencyCommand = new WordFrequencyCommand();

$application->add($wordFrequencyCommand);
$application->setDefaultCommand($wordFrequencyCommand->getName(), true);

$application->run();
